name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
